In [0]:
import numpy as np


1) Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas

In [0]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])

In [0]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

Найдите ковариацию этих двух величин с помощью элементарных действий

In [0]:
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)

In [8]:
cov

9157.839999999997

Найдите ковариацию этих двух величин  с помощью функции cov из numpy 

In [11]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [15]:
np.cov(zp, ks, ddof=1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков

In [12]:
np.std(zp)

59.115480206118605

In [13]:
np.std(ks)

174.55340157098058

In [14]:
9157.84/(59.115480206118605*174.55340157098058)

0.8874900920739162

In [16]:
np.std(zp, ddof=1)

62.31318747531162

In [17]:
np.std(ks, ddof=1)

183.99544076477068

In [18]:
10175.37777778/(62.31318747531162*183.99544076477068)

0.88749009207411

Найдите коэффициент корреляции Пирсона с помощью функций из библиотек numpy и pandas

In [8]:
np.corrcoef(ks, zp)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

2) Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

так как средн квадратичное отклонение не известо то используем формулу X(средн) +- t(a/2)*сигма/(корень из n)

In [0]:
import math

In [0]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [0]:
Xs = np.mean(iq)

In [22]:
Xs

118.1

In [24]:
np.std(iq, ddof=1)

10.54566788359614

In [0]:
X1 = Xs - 2.262*np.std(iq, ddof=1)/math.sqrt(10)

In [43]:
X1

110.55660776308164

In [0]:
X2 = Xs + 2.262*np.std(iq, ddof=1)/math.sqrt(10)

In [45]:
X2

125.64339223691834

3) Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

так как дисперсия известна, то используем формулу X(средн) +- z(a/2)*сигма/(корень из n)

In [0]:
Xsr = 174.2

In [0]:
H1 = Xsr - 1.96*math.sqrt(25)/math.sqrt(27)

In [49]:
H1

172.31398912064722

In [0]:
H2 = Xsr + 1.96*math.sqrt(25)/math.sqrt(27)

In [51]:
H2

176.08601087935276